site_name: WebtoonScraper
site_description: Download webtoons with ease.
site_url: https://webtoonscraper.readthedocs.org/

theme:
    name: 'material'
    custom_dir: 'docs/overrides'
    palette:
      - scheme: 'default'
        media: '(prefers-color-scheme: light)'
        toggle:
          icon: 'material/lightbulb'
          name: "Switch to dark mode"
      - scheme: 'slate'
        media: '(prefers-color-scheme: dark)'
        primary: 'blue'
        toggle:
          icon: 'material/lightbulb-outline'
          name: 'Switch to light mode'

repo_name: ilotoki0804/WebtoonScraper
repo_url: https://github.com/ilotoki0804/WebtoonScraper/
edit_uri: ""

nav:
    - English README: 'docs/README-en.md'
    - 저작권과 책임: 'docs/copyright.md'
    - 사용 가이드:
      - 앱: 'docs/app-guide.md'
      - 실행 파일: 'docs/executable-guide.md'
      - PyPI 패키지: 'docs/how-to-use.md'
      - 플랫폼 가이드: 'docs/platforms.md'
    - 릴리즈 노트: 'docs/releases.md'

markdown_extensions:
  - admonition
  - codehilite:
      css_class: highlight
  - mkautodoc

# extra_css:
#     - css/custom.css
